Headless Service Enabled Value
grafana/mimir pull request #2606
Opened 2022-07-31 05:26 UTC by BrandonDalton

#### What this PR does

#### Which issue(s) this PR fixes or relates to

Fixes #<issue number>

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2022-08-15 14:32 UTC, dimitarvdimitrov reviewed
Thank you for the contribution. I left a few comments

2022-08-15 14:32 UTC, dimitarvdimitrov commented on operations/helm/charts/mimir-distributed/values.yaml
> +  headlessService:
This is mentioned in the migration docs in `migrating-from-cortex.md`. Can you edit that file too so that it doesn't refer to the headless service?

2022-09-13 07:05 UTC, krajorama requested changes
Hi, I think we should solve this some other way as the multi zone PR will rely on the headless service when there are multi zone ingesters/store-gateways. Can we add some annotation instead to make the annotation sets different?

2022-10-07 09:52 UTC, pracucci commented
The CHANGELOG has just been cut to prepare for the next Mimir release. Please rebase `main` and eventually move the CHANGELOG entry added / updated in this PR to the top of the CHANGELOG document. Thanks!

2023-01-18 13:59 UTC, pracucci commented
_Closing for now, being stale._

2023-01-18 13:59 UTC, closed without merging