Helm: add autoscaling/v2 horizontalPodAutoscaler
grafana/mimir pull request #2848
Opened 2022-08-26 08:36 UTC by dimitarvdimitrov

#### What this PR does

The autoscaling/v2beta1 HorizontalPodAutoscaler is [removed in Kubernetes 1.25](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125) in favour of autoscaling/v2. This creates a different resource for the HPA if the kubernetes version is >=1.25.

I still haven't tested that the below works on 1.25, but the manifests seem to comply with the [API spec](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/#HorizontalPodAutoscalerSpec).

Keeping in draft until I can verify this works with 1.25

#### Which issue(s) this PR fixes or relates to

Related to https://github.com/grafana/mimir/issues/2201

#### Checklist

- NA Tests updated
- NA Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2022-08-31 12:18 UTC, dimitarvdimitrov commented
i tested this on 1.25 and it seems to work.

2022-09-16 08:51 UTC, krajorama requested changes

2022-09-16 09:05 UTC, dimitarvdimitrov commented on operations/helm/charts/mimir-distributed/CHANGELOG.md
> +* [ENHANCEMENT] Support autoscaling/v2 HorizontalPodAutoscaler for nginx autoscaling. This is enabled by default on Kubernetes >= 1.25. #2848
I'm not sure what I meant tbh. The below sounds more accurate
```suggestion
* [ENHANCEMENT] Support autoscaling/v2 HorizontalPodAutoscaler for nginx autoscaling. This is used when deploying on Kubernetes >= 1.25. #2848
```

2022-09-16 09:23 UTC, krajorama approved these changes

2022-09-16 09:39 UTC, merged