Add useful helm chart scripts
grafana/mimir pull request #2868
Opened 2022-08-31 12:59 UTC by jesusvazquez

This commit is adding two new scripts to:
- Bootstrap a new kind cluster with mimir-distributed installed.
- Generate an enterprise tenant token given a mimir-distributed
  installation with enterprise enabled.

2022-09-16 11:09 UTC, krajorama requested changes
Cool. Is this for internal use or intended for anybody?

2022-09-16 11:09 UTC, krajorama commented on operations/helm/charts/mimir-distributed/scripts/bootstrap_kind_cluster.sh
> +# Enterprise and graphite enabled
Super weird to have this commented out. I'd suggest to make the license file a CLI flag, then the script can decide what to do.

2022-09-19 14:41 UTC, dimitarvdimitrov approved these changes
Hey, sorry I dropped the ball on this one. LGTM with two nitpicks to make these scripts easier to use in CI

@krajorama these are internal for now. I am planning on making them run as a test hook when users do `helm test` and graphite is enabled.

2022-09-19 14:41 UTC, dimitarvdimitrov commented on operations/helm/charts/mimir-distributed/scripts/test_graphite_write_path.sh
> +  "${MIMIR_GATEWAY_HOST}:8080/graphite/metrics" -d  "${data}"
This should change the exit code of curl when the status code is >= 400
```suggestion
  --fail-with-body \
  "${MIMIR_GATEWAY_HOST}:8080/graphite/metrics" -d  "${data}"
```

2022-09-19 14:41 UTC, dimitarvdimitrov commented on operations/helm/charts/mimir-distributed/scripts/test_graphite_read_path.sh
> +  "${MIMIR_GATEWAY_HOST}:8080/graphite/tags"
This should change the exit code of curl when the status code is >= 400
```suggestion
  --fail-with-body \
  "${MIMIR_GATEWAY_HOST}:8080/graphite/tags"
```

2022-09-22 15:53 UTC, jesusvazquez commented
@dimitarvdimitrov addressed your feedback and @krajorama 's as well

2022-09-23 18:07 UTC, dimitarvdimitrov approved these changes

2022-09-26 10:17 UTC, krajorama approved these changes

2022-09-26 10:18 UTC, merged