Helm: Clean up default rollout strategies
grafana/mimir pull request #3029
Opened 2022-09-23 11:22 UTC by dimitarvdimitrov

Remove `{maxSurge:0, maxUnavailable:1}` for distributor,
overrides_exporter, querier, query_frontend, admin_api, gateway,
graphite_{querier,write_proxy,web}. This uses the default values of
`{maxSurge:25% (rounded up), maxUnavailable:25% (rounded down)}`.

This change allows to do zero-downtime rollouts for these components
when replicas==1. This was affecting the distributor, query_frontend,
admin_api, gateway.

Related to #2890 

Signed-off-by: Dimitar Dimitrov <dimitar.dimitrov@grafana.com>

2022-10-07 09:50 UTC, pracucci commented
The CHANGELOG has just been cut to prepare for the next Mimir release. Please rebase `main` and eventually move the CHANGELOG entry added / updated in this PR to the top of the CHANGELOG document. Thanks!

2022-10-14 07:29 UTC, krajorama requested changes

2022-10-14 07:29 UTC, krajorama commented on operations/helm/charts/mimir-distributed/CHANGELOG.md
> +* [ENHANCEMENT] Clean up default rollout strategies. Now distributor, overrides_exporter, querier, query_frontend, admin_api, gateway, and graphite components rollout with a single replica when witho
needs rebase

2022-10-14 07:29 UTC, krajorama commented on operations/helm/charts/mimir-distributed/CHANGELOG.md
> +* [ENHANCEMENT] Clean up default rollout strategies. Now distributor, overrides_exporter, querier, query_frontend, admin_api, gateway, and graphite components rollout with a single replica when witho
```suggestion
* [ENHANCEMENT] Improve default rollout strategies. Now distributor, overrides_exporter, querier, query_frontend, admin_api, gateway, and graphite components can be upgraded more quickly and also can be rolled out with a single replica without downtime. #3029
```

2022-10-14 08:25 UTC, dimitarvdimitrov commented
I think I addressed everything, PTAL @krajorama

2022-10-14 08:45 UTC, krajorama approved these changes
LGTM

2022-10-14 11:26 UTC, merged