helm: use mimir for nginx ingress examples
grafana/mimir pull request #3336
Opened 2022-10-29 04:49 UTC by paulroche

#### What this PR does

updates example within helm chart to remove reference to loki and replaces them with mimir

#### Which issue(s) this PR fixes or relates to

Fixes #

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2022-10-29 04:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/mimir?pullRequest=3336) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/mimir?pullRequest=3336) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/mimir?pullRequest=3336) it.</sub>

2022-10-30 04:28 UTC, Logiraptor requested changes
Thanks for cleaning this up!

Can you please add an entry to the [CHANGELOG](https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/CHANGELOG.md#main--unreleased) under the "main / unreleased" section?

Also, can you run `make build-helm-tests` and commit the results to fix the failing lint step?

Thanks!

2022-11-08 06:35 UTC, paulroche commented
@Logiraptor changelog and tests updated

2022-11-08 15:20 UTC, Logiraptor approved these changes

2022-11-08 15:20 UTC, Logiraptor commented
Amazing, thanks for your contribution 😃

2022-11-08 15:20 UTC, merged