Add schema to DNS service discovery docs
grafana/mimir pull request #3450
Opened 2022-11-15 11:33 UTC by daquinoaldo

The missing schema leads to errors like `improperly formatted alertmanager URL "alertmanager.mimir.svc.cluster.local:8080/alertmanager" (maybe the scheme is missing?)`.

- [ ] Tests updated
- [x] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2022-11-15 11:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/mimir?pullRequest=3450) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/mimir?pullRequest=3450) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/mimir?pullRequest=3450) it.</sub>

2022-11-15 12:03 UTC, pracucci requested changes
Thanks for opening this PR! The issue you raised is interesting. The doc page `docs/sources/operators-guide/configure/about-dns-service-discovery.md` is a generic one about the DNS-based service discovery. In the example you edited there (memcached one) it's correct to **not** have a schema (e.g. memcached protocol is not HTTP based). However, when you use the DNS-based service discovery with the alertmanager, you need to set the scheme there.

We can do few things to clarify it:
1. In `docs/sources/operators-guide/configure/about-dns-service-discovery.md`, mention the scheme is required when referencing the config option `-ruler.alertmanager-url`
2. We can improve the CLI flag description [here](https://github.com/grafana/mimir/blob/8329c5cba240a16cdf4a8fe51a54573c05cceb61/pkg/ruler/ruler.go#L144) to clarify it there as well

2022-11-15 18:08 UTC, daquinoaldo commented
Thank you, @pracucci. I've updated the PR.

2022-11-16 05:24 UTC, pracucci approved these changes
LGTM. Could you run `make reference-help doc` to update the auto-generated doc, please? @osg-grafana can you take a final look at the copy, please?

2022-11-16 14:32 UTC, osg-grafana commented on docs/sources/operators-guide/configure/about-dns-service-discovery.md
> +The Alertmanager URL must contain also the scheme. For example: `dns+http://alermanager.local:8080`.
Word order

2022-11-16 14:32 UTC, osg-grafana approved these changes
Unblocking with feedback

2022-11-17 12:33 UTC, jhesketh approved these changes

2022-11-17 13:31 UTC, merged