Make use stable v1 PodDisruptionBudget
grafana/mimir pull request #4337
Opened 2023-03-01 14:47 UTC by Siebjee

Use stable v1 PodDisruptionBudget rather than deprecated v1beta1 when deploying read-write deployment mode

#### What this PR does
Fixes the use of the removed `policy/v1beta1` in kubernetes 1.25

Fixes #4336

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2023-03-01 14:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/mimir?pullRequest=4337) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/mimir?pullRequest=4337) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/mimir?pullRequest=4337) it.</sub>

2023-03-01 15:45 UTC, krajorama requested changes
We already select the version based on the kubernetes version so this should not happen if helm can get the kubernetes version from the actual server.

If you are using helm offline (for example in CI/CD with Kustomise), it can happen that helm does not know the version. In such case, please use this kind of override to set it : https://github.com/grafana/mimir/blob/2f31dae8047a6deb57bb15746bb7c6a9b9b01fe8/operations/helm/charts/mimir-distributed/ci/offline/test-enterprise-k8s-1.25-values.yaml#L2

e.g.
```
# Pin kube version so results are the same for running in CI and locally where the installed kube version may be different.
kubeVersionOverride: "1.25"
```

2023-03-01 15:45 UTC, krajorama commented on CHANGELOG.md
> +* [CHANGE] Make use stable `policy/v1` in distributed helm chart. #4337
This needs to go in the helm Changelog https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/CHANGELOG.md

2023-03-01 15:45 UTC, krajorama commented on operations/helm/charts/mimir-distributed/templates/podsecuritypolicy.yaml
> +apiVersion: policy/v1
We don't even try to install PodSecutiryPolicy on 1.25 and above, due to https://github.com/grafana/mimir/blob/6ca0f9c033a53864194fd55a7744caf539628e1a/operations/helm/charts/mimir-distributed/templates/_helpers.tpl#L437

2023-03-01 15:45 UTC, krajorama commented on operations/helm/charts/mimir-distributed/templates/_helpers.tpl
> +    {{- print "policy/v1" -}}
We select the correct version in this template due to the version check

2023-03-01 16:31 UTC, Siebjee commented
I was already confused why it did not want to detect my changes. Yes I am using kustomize! Let me confirm this indeed fixes my issue.

2023-03-01 17:02 UTC, Siebjee commented
> We already select the version based on the kubernetes version so this should not happen if helm can get the kubernetes version from the actual server.
> 
> If you are using helm offline (for example in CI/CD with Kustomise), it can happen that helm does not know the version. In such case, please use this kind of override to set it :
> 
> https://github.com/grafana/mimir/blob/2f31dae8047a6deb57bb15746bb7c6a9b9b01fe8/operations/helm/charts/mimir-distributed/ci/offline/test-enterprise-k8s-1.25-values.yaml#L2
> 
> e.g.
> 
> ```
> # Pin kube version so results are the same for running in CI and locally where the installed kube version may be different.
> kubeVersionOverride: "1.25"
> ```

Somehow this does not work. I still get the same error described in #4336

2023-03-02 11:14 UTC, lamida commented
@Siebjee I replied to you in #4336.

2023-03-02 12:07 UTC, Siebjee commented
Closing PR as most likely this whole endeavour was a slight oversight on my part.

2023-03-02 12:07 UTC, closed without merging