Update ingester.md
grafana/mimir pull request #4827
Opened 2023-04-24 18:38 UTC by willychrisza

minor changes for clarity

#### What this PR does

#### Which issue(s) this PR fixes or relates to

Fixes #<issue number>

#### Checklist

- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

2023-04-24 18:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/mimir?pullRequest=4827) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/mimir?pullRequest=4827) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/mimir?pullRequest=4827) it.</sub>

2023-04-25 11:56 UTC, dimitarvdimitrov approved these changes

2023-04-25 11:59 UTC, osg-grafana requested changes
Needs doc review

2023-04-25 11:59 UTC, dimitarvdimitrov commented
the changes seem ok and correct, but I'm not sure if we want to break the consistency with the other components - the title is `Grafana Mimir <component>` whereas this changes it to `Understanding <component>`.

Also if we do decide to go with the new format, it will be great if we don't break existing links.

2023-04-25 12:05 UTC, osg-grafana commented on docs/sources/mimir/operators-guide/architecture/components/ingester.md
> +Incoming time series data from [distributors]({{< relref "distributor.md" >}}) is temporarily stored in the ingester's memory or offloaded to disk before being written to long-term storage.
As odd as it sounds, "data" is plural.

2023-04-25 12:06 UTC, osg-grafana commented on docs/sources/mimir/operators-guide/architecture/components/ingester.md
> +# Understanding the Grafana Mimir Ingester Component
```suggestion
# Grafana Mimir ingester
```
The title must match the metadata, and the other components have parallel structure to the original. Reverting.

2023-04-25 12:35 UTC, willychrisza commented on docs/sources/mimir/operators-guide/architecture/components/ingester.md
> +Incoming time series data from [distributors]({{< relref "distributor.md" >}}) is temporarily stored in the ingester's memory or offloaded to disk before being written to long-term storage.
oh gosh, i did know this once

2023-04-25 14:51 UTC, osg-grafana commented on docs/sources/mimir/operators-guide/architecture/components/ingester.md
> +If an ingester process crashes or exits abruptly, any in-memory time series data that has not yet been uploaded to long-term storage may be lost.
```suggestion
If an ingester process crashes or exits abruptly, any in-memory time series data that have not yet been uploaded to long-term storage may be lost.
```

2023-04-25 14:52 UTC, osg-grafana commented on docs/sources/mimir/operators-guide/architecture/components/ingester.md
> +Unlike sole replication, the WAL ensures that in-memory time series data is not lost in the event of multiple ingester failures. Each ingester can recover the data from the WAL after a subsequent res
```suggestion
Unlike sole replication, the WAL ensures that in-memory time series data are not lost in the case of multiple ingester failures. Each ingester can recover the data from the WAL after a subsequent restart.
```
"event" is overloaded in our industry, so changing word to "case".

2023-04-27 04:32 UTC, pracucci commented
Thanks for contributing to doc! I committed the Ursula's edits to move forward with this PR. @osg-grafana can you take a final look, please?

2023-04-27 17:16 UTC, merged