Ensure cardinality estimate cache keys are valid
grafana/mimir pull request #7043
Opened 2024-01-03 18:19 UTC by 56quarters

#### What this PR does

Ensure that cache keys generated from cardinality estimate middleware are less than 250 bytes in length by hashing the tenant IDs that are included in them. This is especially evident when using tenant federation where multiple tenant IDs in a request.

#### Which issue(s) this PR fixes or relates to

Fixes #6931

#### Checklist

- [X] Tests updated.
- [NA] Documentation added.
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

2024-01-04 08:19 UTC, dimitarvdimitrov approved these changes
LGTM

2024-01-04 10:42 UTC, pracucci requested changes
Sorry to block this, but so far it was done on purpose for security reasons. The hashing function is not cryptographically secure and so we may have cross-tenant cache pollution leading to security issues. That's why the tenant ID should be never hashed in Mimir (please advise if you find any place where it's hashed).

2024-01-04 14:55 UTC, 56quarters commented
> Sorry to block this, but so far it was done on purpose for security reasons. The hashing function is not cryptographically secure and so we may have cross-tenant cache pollution leading to security issues. That's why the tenant ID should be never hashed in Mimir (please advise if you find any place where it's hashed).

OK, I will close this PR. Do you have any suggestions for fixing #6931?

Potential options I can see
* Hash tenant IDs with a cryptographic hash
* Check the length of the key before trying to use it and skip the cardinality estimate in this case
* Leave things as-is and let the client ensure the key is valid and continue to return an error when it's not

2024-01-04 14:55 UTC, closed without merging

2024-01-09 09:36 UTC, pstibrany commented
I think either using crypto-hash or storing tenant ID into value and checking it after reading the cached item would work.