Alertmanager: Implement experimental /templates/test API
grafana/mimir pull request #8608
Opened 2024-07-04 13:53 UTC by fayzal-g

#### What this PR does
This PR adds experimental functionality to test templates under `api/v1/grafana/templates/test`.

#### Checklist

- [ ] Tests updated.
- [ ] Documentation added.
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [ ] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

2024-07-05 09:49 UTC, santihernandezc requested changes

2024-07-05 09:49 UTC, santihernandezc commented on integration/e2emimir/client.go
> +	}
I'm getting JSON field names capitalized, we should add JSON struct tags in the Alerting repo for `TestTemplatesResults`.

2024-07-05 09:49 UTC, santihernandezc commented on pkg/alertmanager/alertmanager.go
> +
We're not returning after calling `http.Error()`, so the function continues executing and writing to the response writer. HTTP response I got (summarized):

```bash
HTTP/1.1 400 Bad Request
Content-Type: application/json

error unmarshalling test templates config JSON: invalid character '}' after object key
{"Results":null,"Errors":null}
```

In any case, submitting a bad request to Grafana's current template testing endpoint results in a JSON response. Any reason why we're not following the same pattern here?

2024-07-05 09:49 UTC, santihernandezc commented on pkg/alertmanager/alertmanager.go
> +			http.StatusBadRequest)
```suggestion
		http.Error(w,
			fmt.Sprintf("error unmarshalling test templates config JSON: %s", err.Error()),
			http.StatusBadRequest)
		return
```

2024-07-05 09:49 UTC, santihernandezc commented on pkg/alertmanager/alertmanager.go
> +			http.StatusInternalServerError)
```suggestion
		http.Error(w,
			fmt.Sprintf("error testing templates: %s", err.Error()),
			http.StatusInternalServerError)
		return
```

2024-07-05 09:49 UTC, santihernandezc commented on pkg/alertmanager/distributor.go
> +	return false
We can condense this into one line:

```suggestion
	return strings.HasSuffix(p, "/silences") || strings.HasSuffix(p, "/api/v1/grafana/templates/test")
```

2024-07-09 07:40 UTC, ying-jeanne commented
Hi, thanks for the PR, do you also needs this to be vendored for template test? https://github.com/grafana/mimir/pull/8560/files, it would be nice if someone knows well alert gives this PR a review

2024-07-09 16:16 UTC, santihernandezc approved these changes
LGTM, nice job 😎

2024-07-10 13:04 UTC, aknuds1 approved these changes
LGTM modulo nits.

2024-07-10 13:04 UTC, aknuds1 commented on integration/e2emimir/client.go
> +		return nil, fmt.Errorf("error creating request: %v", err)
[Nit] Might as well be consistent :)
```suggestion
		return nil, fmt.Errorf("error creating request: %s", err)
```

2024-07-10 13:04 UTC, aknuds1 commented on integration/e2emimir/client.go
> +		return nil, fmt.Errorf("testing templates failed with status %d and error %v", resp.StatusCode, string(body))
[Nit] Might as well be precise about the type:
```suggestion
		return nil, fmt.Errorf("testing templates failed with status %d and error %s", resp.StatusCode, string(body))
```

2024-07-10 13:39 UTC, merged