Mimir query engine: improve performance of `TestBothEnginesReturnSameResultsForBenchmarkQueries` and `TestBenchmarkSetup`
grafana/mimir pull request #8963
Opened 2024-08-12 06:28 UTC by charleskorn

#### What this PR does

This PR improves the performance of two MQE tests, `TestBothEnginesReturnSameResultsForBenchmarkQueries` and `TestBenchmarkSetup`.

It does this by only flushing the ingester used during these tests once, rather than after loading each batch of data.

On my machine, this cuts ~30s off the time taken to run each of these tests:
* `TestBothEnginesReturnSameResultsForBenchmarkQueries`: was 50.1, now 20.2s
* `TestBenchmarkSetup`: was 36.1s, now 6.0s

This does not have a dramatic effect on the performance of setting up the test data used during benchmarks, as this is dominated by the time taken to ingest the data.

#### Which issue(s) this PR fixes or relates to

(none)

#### Checklist

- [n/a] Tests updated.
- [n/a] Documentation added.
- [n/a] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [n/a] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

2024-08-12 06:39 UTC, jhesketh requested changes
This is where we had trouble running this on machines with less memory.

Can you do a profile of the benchmark tool before and after this change please? I think it'll lead to OOMing in some cases.

Instead, we have the `batchSize` on line 217 designed to tune how often a flush occurs. We should tune that to a better value and optionally have it use an environment flag for those with more memory.

2024-08-14 01:02 UTC, charleskorn commented
> Can you do a profile of the benchmark tool before and after this change please? I think it'll lead to OOMing in some cases.

Before this change (tl;dr: tests peak at 1.30 GB RSS, benchmark ingester peaks at 822 MB RSS):

```
pkg/streamingpromql/benchmarks$ go test -c -o tests -tags stringlabels . && time -l -h  ./tests -test.v -test.run="TestBothEnginesReturnSameResultsForBenchmarkQueries" -test.count=1

<snip>

  54.05s real   23.89s user   7.31s sys
          1303986176  maximum resident set size
                   0  average shared memory size
                   0  average unshared data size
                   0  average unshared stack size
               80118  page reclaims
                 485  page faults
                   0  swaps
                   0  block input operations
                   0  block output operations
                5052  messages sent
                5010  messages received
                7644  signals received
               62611  voluntary context switches
              180703  involuntary context switches
        285496870362  instructions retired
         77642138811  cycles elapsed
          1258557760  peak memory footprint


tools/benchmark-query-engine$ go build -tags stringlabels . && command time -l -h ./benchmark-query-engine -start-ingester

<snip>

	1m36.00s real		1m16.28s user		11.88s sys
           822231040  maximum resident set size
                   0  average shared memory size
                   0  average unshared data size
                   0  average unshared stack size
               54873  page reclaims
                 455  page faults
                   0  swaps
                   0  block input operations
                   0  block output operations
                   9  messages sent
                   9  messages received
               20670  signals received
               71493  voluntary context switches
             1647464  involuntary context switches
       1051284592543  instructions retired
        259614041582  cycles elapsed
           756141952  peak memory footprint

```

After this change (tl;dr: tests peak at 1.25 GB RSS, benchmark ingester peaks at 2.53 GB RSS):

```
pkg/streamingpromql/benchmarks$ go test -c -o tests -tags stringlabels . && time -l -h  ./tests -test.v -test.run="TestBothEnginesReturnSameResultsForBenchmarkQueries" -test.count=1

<snip>

	19.09s real		17.61s user		1.45s sys
          1252556800  maximum resident set size
                   0  average shared memory size
                   0  average unshared data size
                   0  average unshared stack size
               76403  page reclaims
                 485  page faults
                   0  swaps
                   0  block input operations
                   0  block output operations
                4851  messages sent
                4779  messages received
                3138  signals received
                9422  voluntary context switches
               50562  involuntary context switches
        244640504380  instructions retired
         57986569660  cycles elapsed
          1214075072  peak memory footprint

tools/benchmark-query-engine$ go build -tags stringlabels . && command time -l -h ./benchmark-query-engine -start-ingester

<snip>

       1m4.00s real		1m10.25s user		5.16s sys
          2534768640  maximum resident set size
                   0  average shared memory size
                   0  average unshared data size
                   0  average unshared stack size
              173994  page reclaims
                 455  page faults
                   0  swaps
                   0  block input operations
                   0  block output operations
                   9  messages sent
                   9  messages received
                6157  signals received
               15051  voluntary context switches
              214111  involuntary context switches
        816462636390  instructions retired
        230477153096  cycles elapsed
          2502367744  peak memory footprint

```

The main problem seems to be the benchmark setup case - I'll see if I can do anything to improve that.

2024-08-14 01:34 UTC, charleskorn commented
I've tweaked the setup to use batches of 1000 samples, with a flush after every batch, and to reuse the `mimirpb.TimeSeries` instances and slices between batches.

This gives similar performance to flushing after all batches for the test cases, and seems to have made the benchmark setup time noticeably faster (previously it was over a minute, now it's consistently less than 45s). It also returns the peak RSS of the benchmark setup to ~800 MB.

@jhesketh could you give this branch a run on your machine and confirm you don't run into any OOMs?

2024-08-14 04:10 UTC, jhesketh approved these changes
lgtm, thanks for tuning the batchSize

2024-08-14 04:12 UTC, jhesketh commented
> @jhesketh could you give this branch a run on your machine and confirm you don't run into any OOMs?

I ran it without OOM'ing. I didn't measure the memory usage, but watching top the memory seems to go up before flushing about ~1GB peaks.

2024-08-14 04:53 UTC, merged