Add support for lz4 algorithm on distributor
grafana/mimir pull request #9763
Opened 2024-10-28 23:50 UTC by santileira

#### What this PR does

This PR adds support for `lz4` algorithm on the distributor.

#### Which issue(s) this PR fixes or relates to

Fixes #9259

#### Checklist

- [X] Tests updated.
- [X] Documentation added.
- [X] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`.
- [X] [`about-versioning.md`](https://github.com/grafana/mimir/blob/main/docs/sources/mimir/configure/about-versioning.md) updated with experimental features.

2024-10-28 23:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/mimir?pullRequest=9763) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/mimir?pullRequest=9763) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/mimir?pullRequest=9763) it.</sub>

2024-10-28 23:52 UTC, santileira commented on pkg/distributor/otel_test.go
> -			if tt.encoding != "" {
I decided to remove this because we are doing this inside the `createOTLPProtoRequest` function.

2024-10-28 23:53 UTC, santileira commented on pkg/util/http.go
> -	if compression != NoCompression && compression != RawSnappy && compression != Gzip {
I decided to refactor this to have all the logic about how to read the buffer on the same place.

2024-10-29 14:03 UTC, aknuds1 commented
I will check w/ other OTel developers today, to gain a better understanding about the LZ4 support added to OTel Collector.

2024-10-29 16:24 UTC, aknuds1 commented
@santileira out of curiosity, do you have any context on why one would use LZ4 over e.g. Snappy (Mimir supports Snappy for gRPC compression, as a data point)?

2024-10-29 16:56 UTC, aknuds1 requested changes
Please see comments.

2024-10-29 17:13 UTC, santileira commented
> @santileira out of curiosity, do you have any context on why one would use LZ4 over e.g. Snappy (Mimir supports Snappy for gRPC compression, as a data point)?

No TBH. I decided to do this based on the issue.

2024-10-29 17:17 UTC, santileira commented on pkg/distributor/otel.go
> +					reader = lz4.NewCompressingReader(reader)
You are right.

2024-10-29 17:17 UTC, santileira commented on pkg/util/http.go
> +			return nil, errors.Wrap(err, "decompress ")
Done

2024-11-06 14:57 UTC, santileira commented
@aknuds1 could you review the PR again?

2024-11-06 15:08 UTC, aknuds1 commented
Yeah, I'm getting back to it this week I hope. Been a really busy few days.

2024-11-09 10:14 UTC, aknuds1 approved these changes
LGTM, thanks!

2024-11-09 10:41 UTC, aknuds1 requested changes
Tests fail due to an inconsistency. That also made me realize I don't want to drop the "Only" part of the error message, since it only makes it less precise.

2024-11-09 10:41 UTC, aknuds1 commented on pkg/distributor/otel.go
> +			return httpgrpc.Errorf(http.StatusUnsupportedMediaType, "unsupported compression: %s. \"gzip\", \"lz4\", or no compression supported", contentEncoding)
The failing test made me realize I don't want to drop "Only" from the error message:
```suggestion
			return httpgrpc.Errorf(http.StatusUnsupportedMediaType, "unsupported compression: %s. Only \"gzip\", \"lz4\", or no compression supported", contentEncoding)
```

2024-11-09 10:41 UTC, aknuds1 commented on pkg/distributor/otel_test.go
> +			expectedLogs: []string{`level=error user=test msg="detected an error while ingesting OTLP metrics request (the request may have been partially ingested)" httpCode=415 err="rpc error: code = Code(4
```suggestion
			errMessage:   "Only \"gzip\", \"lz4\", or no compression supported",
			expectedLogs: []string{`level=error user=test msg="detected an error while ingesting OTLP metrics request (the request may have been partially ingested)" httpCode=415 err="rpc error: code = Code(415) desc = unsupported compression: snappy. Only \"gzip\", \"lz4\", or no compression supported" insight=true`},
```

2024-11-10 16:56 UTC, aknuds1 approved these changes
LGTM, thanks!

2024-11-10 17:18 UTC, santileira commented
@stevesg could you review it? Thanks

2024-11-10 18:50 UTC, merged